# Generated by Django 5.0.3 on 2024-03-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InvoiceData",
            fields=[
                ("App ID", models.IntegerField()),
                (
                    "Xref",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("Settlement Date", models.DateField()),
                ("Broker", models.CharField(max_length=100)),
                ("Sub Broker", models.CharField(max_length=100)),
                ("Borrower Name", models.CharField(max_length=100)),
                ("Description", models.CharField(max_length=500)),
                ("Total Loan Amount", models.FloatField(editable=False)),
                ("Comission Rate", models.FloatField()),
                ("Upfront", models.FloatField()),
                ("Upfront Incl GST", models.FloatField()),
                ("Tier", models.CharField(max_length=10)),
            ],
        ),
    ]
